// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gihub.com/DarmawanEfendi/flutter_interact_demo/models"
)

// GetProfilesOKCode is the HTTP code returned for type GetProfilesOK
const GetProfilesOKCode int = 200

/*GetProfilesOK successful operation

swagger:response getProfilesOK
*/
type GetProfilesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ProfilesResponse `json:"body,omitempty"`
}

// NewGetProfilesOK creates GetProfilesOK with default headers values
func NewGetProfilesOK() *GetProfilesOK {

	return &GetProfilesOK{}
}

// WithPayload adds the payload to the get profiles o k response
func (o *GetProfilesOK) WithPayload(payload *models.ProfilesResponse) *GetProfilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get profiles o k response
func (o *GetProfilesOK) SetPayload(payload *models.ProfilesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProfilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProfilesBadRequestCode is the HTTP code returned for type GetProfilesBadRequest
const GetProfilesBadRequestCode int = 400

/*GetProfilesBadRequest bad request operation

swagger:response getProfilesBadRequest
*/
type GetProfilesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralErrorResponse `json:"body,omitempty"`
}

// NewGetProfilesBadRequest creates GetProfilesBadRequest with default headers values
func NewGetProfilesBadRequest() *GetProfilesBadRequest {

	return &GetProfilesBadRequest{}
}

// WithPayload adds the payload to the get profiles bad request response
func (o *GetProfilesBadRequest) WithPayload(payload *models.GeneralErrorResponse) *GetProfilesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get profiles bad request response
func (o *GetProfilesBadRequest) SetPayload(payload *models.GeneralErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProfilesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProfilesNotFoundCode is the HTTP code returned for type GetProfilesNotFound
const GetProfilesNotFoundCode int = 404

/*GetProfilesNotFound not found operation

swagger:response getProfilesNotFound
*/
type GetProfilesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralErrorResponse `json:"body,omitempty"`
}

// NewGetProfilesNotFound creates GetProfilesNotFound with default headers values
func NewGetProfilesNotFound() *GetProfilesNotFound {

	return &GetProfilesNotFound{}
}

// WithPayload adds the payload to the get profiles not found response
func (o *GetProfilesNotFound) WithPayload(payload *models.GeneralErrorResponse) *GetProfilesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get profiles not found response
func (o *GetProfilesNotFound) SetPayload(payload *models.GeneralErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProfilesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProfilesInternalServerErrorCode is the HTTP code returned for type GetProfilesInternalServerError
const GetProfilesInternalServerErrorCode int = 500

/*GetProfilesInternalServerError internal server error operation

swagger:response getProfilesInternalServerError
*/
type GetProfilesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralErrorResponse `json:"body,omitempty"`
}

// NewGetProfilesInternalServerError creates GetProfilesInternalServerError with default headers values
func NewGetProfilesInternalServerError() *GetProfilesInternalServerError {

	return &GetProfilesInternalServerError{}
}

// WithPayload adds the payload to the get profiles internal server error response
func (o *GetProfilesInternalServerError) WithPayload(payload *models.GeneralErrorResponse) *GetProfilesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get profiles internal server error response
func (o *GetProfilesInternalServerError) SetPayload(payload *models.GeneralErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProfilesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
