// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gihub.com/DarmawanEfendi/flutter_interact_demo/models"
)

// PostProfileFavouriteCreatedCode is the HTTP code returned for type PostProfileFavouriteCreated
const PostProfileFavouriteCreatedCode int = 201

/*PostProfileFavouriteCreated successful operation

swagger:response postProfileFavouriteCreated
*/
type PostProfileFavouriteCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ProfileResponse `json:"body,omitempty"`
}

// NewPostProfileFavouriteCreated creates PostProfileFavouriteCreated with default headers values
func NewPostProfileFavouriteCreated() *PostProfileFavouriteCreated {

	return &PostProfileFavouriteCreated{}
}

// WithPayload adds the payload to the post profile favourite created response
func (o *PostProfileFavouriteCreated) WithPayload(payload *models.ProfileResponse) *PostProfileFavouriteCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post profile favourite created response
func (o *PostProfileFavouriteCreated) SetPayload(payload *models.ProfileResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProfileFavouriteCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostProfileFavouriteBadRequestCode is the HTTP code returned for type PostProfileFavouriteBadRequest
const PostProfileFavouriteBadRequestCode int = 400

/*PostProfileFavouriteBadRequest bad request operation

swagger:response postProfileFavouriteBadRequest
*/
type PostProfileFavouriteBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralErrorResponse `json:"body,omitempty"`
}

// NewPostProfileFavouriteBadRequest creates PostProfileFavouriteBadRequest with default headers values
func NewPostProfileFavouriteBadRequest() *PostProfileFavouriteBadRequest {

	return &PostProfileFavouriteBadRequest{}
}

// WithPayload adds the payload to the post profile favourite bad request response
func (o *PostProfileFavouriteBadRequest) WithPayload(payload *models.GeneralErrorResponse) *PostProfileFavouriteBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post profile favourite bad request response
func (o *PostProfileFavouriteBadRequest) SetPayload(payload *models.GeneralErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProfileFavouriteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostProfileFavouriteNotFoundCode is the HTTP code returned for type PostProfileFavouriteNotFound
const PostProfileFavouriteNotFoundCode int = 404

/*PostProfileFavouriteNotFound not found operation

swagger:response postProfileFavouriteNotFound
*/
type PostProfileFavouriteNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralErrorResponse `json:"body,omitempty"`
}

// NewPostProfileFavouriteNotFound creates PostProfileFavouriteNotFound with default headers values
func NewPostProfileFavouriteNotFound() *PostProfileFavouriteNotFound {

	return &PostProfileFavouriteNotFound{}
}

// WithPayload adds the payload to the post profile favourite not found response
func (o *PostProfileFavouriteNotFound) WithPayload(payload *models.GeneralErrorResponse) *PostProfileFavouriteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post profile favourite not found response
func (o *PostProfileFavouriteNotFound) SetPayload(payload *models.GeneralErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProfileFavouriteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostProfileFavouriteInternalServerErrorCode is the HTTP code returned for type PostProfileFavouriteInternalServerError
const PostProfileFavouriteInternalServerErrorCode int = 500

/*PostProfileFavouriteInternalServerError internal server error operation

swagger:response postProfileFavouriteInternalServerError
*/
type PostProfileFavouriteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralErrorResponse `json:"body,omitempty"`
}

// NewPostProfileFavouriteInternalServerError creates PostProfileFavouriteInternalServerError with default headers values
func NewPostProfileFavouriteInternalServerError() *PostProfileFavouriteInternalServerError {

	return &PostProfileFavouriteInternalServerError{}
}

// WithPayload adds the payload to the post profile favourite internal server error response
func (o *PostProfileFavouriteInternalServerError) WithPayload(payload *models.GeneralErrorResponse) *PostProfileFavouriteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post profile favourite internal server error response
func (o *PostProfileFavouriteInternalServerError) SetPayload(payload *models.GeneralErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProfileFavouriteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
