// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostProfileFavouriteHandlerFunc turns a function with the right signature into a post profile favourite handler
type PostProfileFavouriteHandlerFunc func(PostProfileFavouriteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostProfileFavouriteHandlerFunc) Handle(params PostProfileFavouriteParams) middleware.Responder {
	return fn(params)
}

// PostProfileFavouriteHandler interface for that can handle valid post profile favourite params
type PostProfileFavouriteHandler interface {
	Handle(PostProfileFavouriteParams) middleware.Responder
}

// NewPostProfileFavourite creates a new http.Handler for the post profile favourite operation
func NewPostProfileFavourite(ctx *middleware.Context, handler PostProfileFavouriteHandler) *PostProfileFavourite {
	return &PostProfileFavourite{Context: ctx, Handler: handler}
}

/*PostProfileFavourite swagger:route POST /profiles/{id}/favourite profile postProfileFavourite

add profile to favourite list

*/
type PostProfileFavourite struct {
	Context *middleware.Context
	Handler PostProfileFavouriteHandler
}

func (o *PostProfileFavourite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostProfileFavouriteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
