// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Swagger Profile
This is profile server only for demo


    Schemes:
      http
    Host: localhost:8080
    BasePath: /
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <darmawan.efendi@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
