// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProfileSchema profile schema
// swagger:model ProfileSchema
type ProfileSchema struct {

	// id of profile
	ID int64 `json:"id,omitempty"`

	// status of favourite
	// Required: true
	IsFavourite *bool `json:"is_favourite"`

	// name of profile
	// Required: true
	Name *string `json:"name"`

	// url of profile
	// Required: true
	URL *string `json:"url"`
}

// Validate validates this profile schema
func (m *ProfileSchema) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIsFavourite(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProfileSchema) validateIsFavourite(formats strfmt.Registry) error {

	if err := validate.Required("is_favourite", "body", m.IsFavourite); err != nil {
		return err
	}

	return nil
}

func (m *ProfileSchema) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ProfileSchema) validateURL(formats strfmt.Registry) error {

	if err := validate.Required("url", "body", m.URL); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProfileSchema) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProfileSchema) UnmarshalBinary(b []byte) error {
	var res ProfileSchema
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
