swagger: '2.0'
info:
  description: 'This is profile server only for demo'
  version: 1.0.0
  title: Swagger Profile
  contact:
    email: darmawan.efendi@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:8080
basePath: /
tags:
  - name: profile
    description: Profile tags
schemes:
  - http
paths:
  /profiles:
    get:
      tags:
        - profile
      summary: Find all profiles
      description: Returns array of profile
      operationId: getProfiles
      produces:
        - application/json
      parameters:
        - name: onlyFavourite
          in: query
          description: query for filter only favourite
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ProfilesResponse'
        '400':
          description: bad request operation
          schema:
            $ref: '#/definitions/GeneralErrorResponse'
        '404':
          description: not found operation
          schema:
            $ref: '#/definitions/GeneralErrorResponse'
        '500':
          description: internal server error operation
          schema:
            $ref: '#/definitions/GeneralErrorResponse'
  /profiles/{id}/favourite:
    post:
      tags:
        - profile
      summary: add profile to favourite list
      description: ''
      operationId: postProfileFavourite
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of profile
          required: true
          type: integer
        - in: body
          name: body
          description: Profile object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/ProfileSchema'
      responses:
        '201':
          description: successful operation
          schema:
            $ref: '#/definitions/ProfileResponse'
        '400':
          description: bad request operation
          schema:
            $ref: '#/definitions/GeneralErrorResponse'
        '404':
          description: not found operation
          schema:
            $ref: '#/definitions/GeneralErrorResponse'
        '500':
          description: internal server error operation
          schema:
            $ref: '#/definitions/GeneralErrorResponse'
definitions:
  MetaSchema:
    type: object
    required:
      - status
      - message
    properties:
      status:
        type: integer
        description: HTTP response code
        example: 200
      message:
        type: string
        description: Message of response
        example: Successfully inserted data
  ProfileSchema:
    type: object
    required:
      - name
      - url
      - is_favourite
    properties:
      id:
        type: integer
        description: id of profile
        example: 1
      name:
        type: string
        description: name of profile
        example: Darmawan Efendi
      url:
        type: string
        description: url of profile
        example: http://www.test.com
      is_favourite:
        type: boolean
        description: status of favourite
        example: false
  GeneralErrorResponse:
    description: General error response
    type: object
    properties:
      meta:
        $ref: '#/definitions/MetaSchema'
  ProfilesResponse:
    description: Response body consist list of profile object
    type: object
    properties:
      meta:
        $ref: '#/definitions/MetaSchema'
      data:
        type: array
        items:
          $ref: '#/definitions/ProfileSchema'
  ProfileResponse:
    description: Response body consist of profile object
    type: object
    properties:
      meta:
        $ref: '#/definitions/MetaSchema'
      data:
        $ref: '#/definitions/ProfileSchema'
          
          
          
            
